### ISSUE TITLE
a)

### ISSUE THREAD

**Issue by danielhrc** [danielhrc/LAB3_TRABHASH#1]
Crie duas implementações de Tabela Hash, sendo uma Linear, com
tratamento de Colisões na Própria Estrutura, com tamanho total de elementos
a ser setada dinamicamente no início da execução, podendo ter no mínimo
tamanho 3 e máximo a capacidade máximo da memória interna.
- [x] Pesquisar sobre implementações de Hash
- [x] Desenvolver o algoritmo
- [x] Testes

**Comment by LucasRotsen** [comment]
OBS: a segunda parte da letra "a" foi colocada na letra "b".

**Comment by danielhrc** [comment]
tudo tranquilo, @Bengtts ?
